/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GuidesZeroDowntimeMigrationRouteImport } from './routes/guides.zero-downtime-migration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesZeroDowntimeMigrationRoute =
  GuidesZeroDowntimeMigrationRouteImport.update({
    id: '/guides/zero-downtime-migration',
    path: '/guides/zero-downtime-migration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/queue': typeof QueueRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/zero-downtime-migration': typeof GuidesZeroDowntimeMigrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/queue': typeof QueueRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/zero-downtime-migration': typeof GuidesZeroDowntimeMigrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/queue': typeof QueueRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/zero-downtime-migration': typeof GuidesZeroDowntimeMigrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/queue'
    | '/sitemap.xml'
    | '/guides/zero-downtime-migration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/queue'
    | '/sitemap.xml'
    | '/guides/zero-downtime-migration'
  id:
    | '__root__'
    | '/'
    | '/logs'
    | '/queue'
    | '/sitemap.xml'
    | '/guides/zero-downtime-migration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  QueueRoute: typeof QueueRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuidesZeroDowntimeMigrationRoute: typeof GuidesZeroDowntimeMigrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/zero-downtime-migration': {
      id: '/guides/zero-downtime-migration'
      path: '/guides/zero-downtime-migration'
      fullPath: '/guides/zero-downtime-migration'
      preLoaderRoute: typeof GuidesZeroDowntimeMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  QueueRoute: QueueRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuidesZeroDowntimeMigrationRoute: GuidesZeroDowntimeMigrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
